# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

import MA_strategy
import yF_Kbar
import RSI_MACD_Strategy
import RSI_MACD_OSC_Strategy

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(759, 910)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 440, 141, 20))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(210, 430, 161, 41))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 810, 141, 41))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 30, 621, 381))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(".\\meme.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(210, 490, 161, 41))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 500, 141, 20))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(40, 580, 211, 131))
        self.groupBox.setObjectName("groupBox")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton.setEnabled(True)
        self.radioButton.setGeometry(QtCore.QRect(30, 30, 121, 21))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.radioButton.setFont(font)
        self.radioButton.setCheckable(True)
        self.radioButton.setChecked(False)
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_2.setEnabled(True)
        self.radioButton_2.setGeometry(QtCore.QRect(30, 60, 121, 21))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setCheckable(True)
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_3.setEnabled(True)
        self.radioButton_3.setGeometry(QtCore.QRect(30, 90, 171, 21))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.radioButton_3.setFont(font)
        self.radioButton_3.setCheckable(True)
        self.radioButton_3.setObjectName("radioButton_3")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(270, 550, 471, 321))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "C109156107王昱翔"))
        self.label_2.setText(_translate("MainWindow", "請輸入股票代號"))
        self.pushButton.setText(_translate("MainWindow", "顯示K線圖"))
        self.label_4.setText(_translate("MainWindow", "回測月數"))
        self.groupBox.setTitle(_translate("MainWindow", "策略選擇"))
        self.radioButton.setText(_translate("MainWindow", "MA交叉"))
        self.radioButton_2.setText(_translate("MainWindow", "RSI + MACD"))
        self.radioButton_3.setText(_translate("MainWindow", "RSI + MACD + OSC"))

        ## 按下button後觸發onClick
        self.pushButton.clicked.connect(self.onClick)

    def onClick(self):
        stock_id = self.lineEdit.text()
        period = self.lineEdit_2.text() + "mo"

        if self.radioButton.isChecked():
            df, KPI_df = MA_strategy.main(stock_id, period)
        elif self.radioButton_2.isChecked():
            df, KPI_df = RSI_MACD_Strategy.main(stock_id, period)
        elif self.radioButton_3.isChecked():
            df, KPI_df = RSI_MACD_OSC_Strategy.main(stock_id, period)

        yF_Kbar.draw_candle_chart(stock_id, df)
        _translate = QtCore.QCoreApplication.translate

        self.tableWidget.setRowCount(KPI_df.shape[0])
        self.tableWidget.setColumnCount(KPI_df.shape[1])

        self.tableWidget.setVerticalHeaderLabels(KPI_df.index)
        self.tableWidget.setHorizontalHeaderLabels(KPI_df.columns)

        count = 0
        for i in KPI_df['數值']:

            # create table
            item = QtWidgets.QTableWidgetItem()
            self.tableWidget.setItem(count , 0, item)

            # 填入資料
            item = self.tableWidget.item(count, 0)
            item.setText(_translate("MainWindow", str(i)))

            count += 1

        self.label.setPixmap(QtGui.QPixmap("stock_Kbar.png"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
